config/routes.rb
Rails.application.routes.draw do

  root 'sessions#new'

  resources :users do
    member do
      get :confirm_email
      get :friends
    end
  end

  resources :sessions, only: [:new, :create, :destroy]
  resources :reset_password, expect: [:destroy]
  resources :relationships, only: [:create, :update, :destroy]
  resources :conversations, expect: [:edit, :update]
  resources :messages, only: [:create]
  resources :rooms, only: [:create, :show, :destroy]

  get '/signup' => 'users#new'
  get '/signin' => 'sessions#new'
  delete '/signout' => 'sessions#destroy'

  get '/help' => 'static_pages#help'
  get '/about' => 'static_pages#about'
  post '/htmlparse' => 'base_chat#html_parse'

end

app/controllers/reset_password_controller.rb
class ResetPasswordController < ApplicationController

  def new
  end

  def create
    @user = User.find_by_email(params[:email].downcase)
    if @user
      @user.send_password_reset
      flash[:info] = 'Email send with instructions'
      redirect_to root_path
    else
      flash.now[:danger] = 'Email invalid'
      render 'new'
    end
  end

  def edit
    @user = User.find_by_password_reset_token(params[:id])
  end

  def update
    @user = User.find_by_password_reset_token(params[:id])

    if @user.password_reset_send_at < 2.hours.ago
      flash[:warning] = 'Reset has expired. Please resend email'
      redirect_to new_reset_password_path

    elsif @user.update_attributes(user_params)
      flash[:success] = 'Password changed'
      redirect_to signin_path

    else
      render 'edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(:password, :password_confirmation)
  end

end

app/views/reset_password/edit.html.erb
<% provide(:title, "Password Reset") %>
<h1>Password reset</h1>

<div class="row">
  <div class="col-xs-6 col-xs-offset-3">

    <%= form_for(@user, url: reset_password_path(params[:id])) do |f| %>

        <%= render 'shared/error_messages' %>

        <div class="form-group">
          <%= f.label :password %>
          <%= f.password_field :password, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :password_confirmation %>
          <%= f.password_field :password_confirmation, class: 'form-control' %>
        </div>

        <%= f.submit 'Update Password', class: 'btn btn-large btn-primary' %>

    <% end %>

  </div>
</div>

app/views/reset_password/new.html.erb
<% provide(:title, "Password Reset") %>
<h1>Password reset</h1>

<div class="row">
  <div class="col-xs-6 col-xs-offset-3">

    <%= form_tag(reset_password_index_path, method: :post) do %>

        <div class="form-group">
          <%= label_tag(:email, 'Email') %>
          <%= text_field_tag(:email, nil, class: 'form-control') %>
        </div>

        <%= submit_tag('Reset password', class: 'btn btn-large btn-primary') %>

    <% end %>

  </div>
</div>

app/views/reset_password/new_pass.html.erb
<% provide(:title, "Password Reset") %>
<h1>Password reset</h1>

<div class="row">
  <div class="col-xs-6 col-xs-offset-3">

    <%= form_for(@user, url: reset_password_path(params[:id])) do |f| %>

        <%= render 'shared/error_messages' %>

        <%= f.label :password %>
        <%= f.password_field :password %>


        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation %>

        <%= f.submit "Update Password", class: "btn btn-large btn-primary" %>

    <% end %>

  </div>
</div>