config/routes.rb
Rails.application.routes.draw do

  root 'sessions#new'

  resources :users do
    member do
      get :confirm_email
      get :friends
    end
  end

  resources :sessions, only: [:new, :create, :destroy]
  resources :reset_password, expect: [:destroy]
  resources :relationships, only: [:create, :update, :destroy]
  resources :conversations, expect: [:edit, :update]
  resources :messages, only: [:create]
  resources :rooms, only: [:create, :show, :destroy]

  get '/signup' => 'users#new'
  get '/signin' => 'sessions#new'
  delete '/signout' => 'sessions#destroy'

  get '/help' => 'static_pages#help'
  get '/about' => 'static_pages#about'
  post '/htmlparse' => 'base_chat#html_parse'

end

app/models/conversation.rb
class Conversation < ActiveRecord::Base

  include ConversationBase

  belongs_to :sender, class_name: 'User', foreign_key: 'sender_id'
  belongs_to :recipient, class_name: 'User', foreign_key: 'recipient_id'
  has_many :messages, as: :dialog

  validates :sender_id, presence: true,
            uniqueness: { scope: :recipient_id }
  validates :recipient_id, presence: true
  validate :conversation_unique

  delegate :login, :show_avatar, to: :recipient, prefix: true
  delegate :login, :show_avatar, to: :sender, prefix: true
  delegate :unread_messages, to: :messages

  scope :between, -> (recipient_id, sender_id) do
    where("(conversations.sender_id = ? AND conversations.recipient_id =?) OR (conversations.sender_id = ? AND conversations.recipient_id =?)",
          sender_id,recipient_id, recipient_id, sender_id)
  end

  scope :involving, -> (user_id) do
    where("conversations.sender_id = ? OR conversations.recipient_id = ?", user_id, user_id)
  end

  def interlocutor?(user)
    user == self.recipient || user == self.sender
  end

  private

  def conversation_unique
    if self.recipient && self.sender
      errors.add(:base, 'They are not unique') if Conversation.between(self.recipient.id, self.sender.id).present?
    end
  end
end

app/controllers/conversations_controller.rb
class ConversationsController < BaseChatController

  def create
    @conversation = current_user.begin_conversation(params[:conversation][:recipient_id])
    redirect_to @conversation
  end

  def index
    @conversations = current_user.show_conversations
  end

  def show
    @conversation = Conversation.find_by(id: params[:id])
    read_unread_messages(@conversation.unread_messages)
    @messages = get_messages_by_params(@conversation.messages)
  end

  def destroy
    Conversation.find_by(id: params[:id]).destroy!
    super
  end

  private

  def interlocutor
    conversation = Conversation.find_by(id: params[:id])
    redirect_to current_user if conversation.nil? || !conversation.interlocutor?(current_user)
  end

end

app/views/conversations/_conversation.html.erb
<li class="<%= unread_message_class(conversation.unread_messages) %>">
  <div class ="row">
    <div class="col-md-2">
      <%= image_tag(conversation.recipient_show_avatar(:thumb)) %>
    </div>
    <div class="col-md-2">
      <%= link_to conversation.recipient_login, conversation.recipient, class: 'conversation_recipient' %>
    </div>
    <div class="col-md-6">
        <%= link_to conversation.last_message[0..50], conversation, class: 'conversation_last_message' %>
    </div>
    <div class="col-md-2">
      <%= link_to 'delete', conversation, method: :delete, data: { confirm: 'Are you sure?' }, class: 'delete_user_link' %>
    </div>
  </div>
</li>

app/views/conversations/_create_room_modal.html.erb
<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Room creating</h4>
      </div>

      <div class="modal-body">
        <%= form_for(current_user.rooms.build) do |f| %>
          <%= f.label :name, 'Chat name:' %>
          <%= f.text_field :name, class: 'chat_name_field' %>
          <div class="checkbox_form">
            <%= f.collection_check_boxes :users, current_user.friends.all, :id, :login do |b| %>
              <div class="collection_check_box">
                <%= b.check_box %>
                <%= b.label %>
              </div>
            <% end %>
          </div>
          <div class="col-md-5 col-md-offset-7">
            <%= f.submit 'Begin conversation', class: 'btn btn-info' %>
          </div>
        <% end %>
      </div>

      <div class="modal-footer"></div>
    </div>
  </div>
</div>

app/views/conversations/index.html.erb
<% provide(:title, 'Messages') %>
<div class = "row">
  <%= render 'users/user_sidebar' %>
  <div class="col-md-9">
    <h1>Messages</h1>
    <div class="row">
      <div class="col-md-3 col-md-offset-11">
        <%= link_to 'Create room', '#myModal', class: 'btn btn-success modal_link', "data-toggle": 'modal' %>
      </div>
      <%= render 'create_room_modal' %>
    </div>
    <div class = "row">
      <ul class="conversations">
        <%= render @conversations %>
      </ul>
    </div>
  </div>
</div>

app/views/conversations/show.html.erb
<% provide(:title, 'Messages') %>

<div class = "row">
  <%= render 'users/user_sidebar' %>
  <div class="col-md-9">

    <%= render 'layouts/messages_list' %>

    <div class = "row">

      <div class="col-md-2">
        <div class = "recipient_image">
          <%= image_tag(current_user.show_avatar(:thumb), alt: current_user.login) %>
        </div>
      </div>

      <%= form_for(Message.new(sender_id: current_user.id, dialog_id: @conversation.id,
                               dialog_type: 'Conversation'), remote: true) do |f| %>

        <%= f.hidden_field :sender_id %>
        <%= f.hidden_field :dialog_id %>
        <%= f.hidden_field :dialog_type %>

        <div class="col-md-10">
          <%= f.text_area :text, rows: 4, id: 'message_text', class: "form-control" %>
        </div>
        <div class = "col-md-3 col-md-offset-9">
          <%= f.submit "Send", class: "btn btn-info" %>
        </div>

      <% end %>
    </div>
    <%= render 'layouts/link_preview' %>
  </div>
</div>

<%= subscribe_to conversation_path(@conversation) %>