config/routes.rb
Rails.application.routes.draw do

  root 'sessions#new'

  resources :users do
    member do
      get :confirm_email
      get :friends
    end
  end

  resources :sessions, only: [:new, :create, :destroy]
  resources :reset_password, expect: [:destroy]
  resources :relationships, only: [:create, :update, :destroy]
  resources :conversations, expect: [:edit, :update]
  resources :messages, only: [:create]
  resources :rooms, only: [:create, :show, :destroy]

  get '/signup' => 'users#new'
  get '/signin' => 'sessions#new'
  delete '/signout' => 'sessions#destroy'

  get '/help' => 'static_pages#help'
  get '/about' => 'static_pages#about'
  post '/htmlparse' => 'base_chat#html_parse'

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :relationships, dependent: :destroy
  has_many :inverted_relationships, foreign_key: 'friend_id', class_name: 'Relationship', dependent: :destroy
  has_many :friends, -> { where(relationships: { status: Relationship.statuses[:accepted] } )},
           through: :relationships
  has_many :requested_friends, -> { where(relationships: { status: Relationship.statuses[:requested] } )},
           source: :friend, through: :relationships
  has_many :pending_friends, -> { where(relationships: { status: Relationship.statuses[:pending] } )},
           source: :friend, through: :relationships
  has_many :conversations, foreign_key: 'sender_id', dependent: :destroy
  has_many :messages, foreign_key: 'sender_id', dependent: :destroy
  has_many :room_relations, class_name: 'RoomUser', dependent: :destroy
  has_many :rooms, through: :room_relations

  before_save { self.email.downcase! }
  before_create  :create_remember_token, :create_confirm_token
  before_destroy :remove_avatar

  validates :login, presence: true, length: { minimum: 3, maximum: 60 }
  validates :email, presence: true, email: true,
            uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 6, maximum: 60 }, password: true

  # Validates for user avatars
  has_attached_file :avatar, styles: { original: "220x220#", thumb: "90x90#" },
                    storage: :cloudinary,
                    cloudinary_upload_options: {
                      public_id: 'avatar',
                      styles: {
                          thumb: {
                              transformation: [
                                  { :crop => 'thumb', :gravity => 'face' }
                              ]
                          }
                      }
                    },
                    default_url: ENV['DEFAULT_AVATAR_PATH'],
                    path: "#{ Rails.env }/:attachment/:id/:hash.:extension",
                    hash_secret: Rails.application.secrets.secret_key_base,
                    size: { in: 0..500.kilobytes }

  validates_attachment_content_type :avatar, content_type: /^image\/(png|gif|jpeg)/

  has_secure_password

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  def online?
    REDIS.exists(self.id)
  end

  # We update just few fields(without pass)
  def send_password_reset
    self.password_reset_token = User.encrypt(User.new_token)
    self.password_reset_send_at = Time.zone.now
    self.save!(validate: false)
    UserMailer.password_reset(self).deliver_now
  end

  def email_activate
    self.email_confirmed = true
    self.confirm_token = nil
    save!(:validate => false)
  end

  def remove_avatar
    self.avatar.clear unless
      self.avatar.eql?(ENV['DEFAULT_AVATAR_PATH'])
  end

  def show_avatar(args)
    if self.avatar.url.blank?
      default_avatar_path(args)
    else
      self.avatar.url(args, cloudinary: { secure: true })
    end
  end

  def begin_conversation(recipient_id)
    if Conversation.between(self.id, recipient_id).present?
      Conversation.between(self.id, recipient_id).first
    else
      conversations.create!(recipient_id: recipient_id)
    end
  end

  def begin_conference(params)
    transaction do
      room = params[:name].nil? ? rooms.create! : rooms.create!(name: params[:name])
      params[:users].each { |user| room.add_interlocutor(user) } if params[:users].present?
      room
    end
  end

  def show_conversations
    (Conversation.involving(self.id) << Room.involving(self.id)).flatten!
  end

  def friend?(friend)
    relationships.exists?(friend_id: friend.id)
  end

  def friends_with(friend)
    unless self == friend || relationships.exists?(friend_id: friend.id)
      transaction do
        relationships.create!(friend: friend, status: :pending)
        inverted_relationships.create!(user: friend, status: :requested)
      end
    end
  end

  def accept_friendship(friend)
    transaction do
      one_side = relationships.find_by(friend_id: friend.id)
      one_side.update_attribute(:status, :accepted)
      second_side = inverted_relationships.find_by(user_id: friend.id)
      second_side.update_attribute(:status, :accepted)
    end
  end

  def breakup_with(friend)
    transaction do
      relationships.find_by(friend_id: friend.id).destroy!
      inverted_relationships.find_by(user_id: friend.id).destroy!
    end
  end

  private

  def create_remember_token
    self.remember_token = User.encrypt(User.new_token)
  end

  def create_confirm_token
    if self.confirm_token.blank?
      self.confirm_token = User.encrypt(User.new_token)
    end
  end

  def default_avatar_path(args)
    "/images/#{args}/default.png"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :signed_in_user, only: [:index, :edit, :update, :destroy, :friends]
  before_action :correct_user, only: [:edit, :update, :friends]
  before_action :admin_user, only: [:destroy]
  before_action :redirect_current_user, only: [:new, :create]

  def new
    @user = User.new
  end

  def show
    @user = User.find_by(id: params[:id])
    @friends = @user.friends.limit(4)
  end

  def index
    @users = User.paginate(page: params[:page], per_page: 10)
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = 'Almost Done! Please confirm your email'
      UserMailer.email_confirmation(@user).deliver_later
      redirect_to signin_path
    else
      render 'new'
    end
  end

  def edit
    @user = User.find_by(id: params[:id])
  end

  # Before update, we delete old avatar from server
  def update
    @user = User.find_by(id: params[:id])

    @user.remove_avatar unless params[:avatar].blank?

    if @user.update_attributes(user_params)
      flash[:success] = 'Profile successfully updated!'
      redirect_to @user
    else
      render 'edit'
    end
  end

  def confirm_email
    @user = User.find_by_confirm_token(params[:id])
    if @user
      @user.email_activate
      flash[:success] = 'Email confirmed! Now you can sign in'
      redirect_to signin_path
    else
      flash[:danger] = 'Sorry, user does not exist'
      redirect_to root_path
    end
  end

  def friends
    @users = user_friends_by_status(params[:status] || 'accepted')
    if params[:status] == 'pending'
      @show_accept_block = true
    end
  end

  def destroy
    User.find_by(id: params[:id]).destroy
    flash[:success] = 'User destroyed'
    redirect_to users_path
  end

  private

  def user_params
    params.require(:user).permit(:login, :email, :password, :password_confirmation, :avatar)
  end

  def admin_user
    redirect_to current_user unless current_user.admin?
  end

end

app/helpers/users_helper.rb
module UsersHelper

  def user_friends_by_status(status)
    user_list = User.find_by(id: params[:id])
    if status == 'requested'
      user_list.requested_friends.all
    elsif status == 'pending'
      user_list.pending_friends.all
    else
      user_list.friends.all
    end
  end

end

app/views/users/_user.html.erb
<li>
  <%= image_tag(user.show_avatar(:thumb),alt: user.login) %>
  <%= link_to user.login, user %>
  <% if user.online? %>
    <span class="online">online</span>
  <% end %>
  <% if current_user.admin? && !current_user?(user) %>
    <%= link_to 'delete', user, method: :delete, data: { confirm: 'Are you sure?' }, class: 'delete_user_link' %>
  <% end %>
  <% unless current_user == user %>

    <%= render 'user_list_block', user: user %>

  <% end %>
</li>

app/views/users/_user_conversation_block.html.erb
<% if current_user != @user && current_user.friends.include?(@user) %>
  <div class="user_start_conversation">
    <%= form_for(current_user.conversations.build(recipient_id: @user.id)) do |f| %>
        <%= f.hidden_field :recipient_id %>
        <%= f.submit 'Begin conversation', class: 'btn btn-info' %>
    <% end %>
  </div>
<% end %>

app/views/users/_user_friends_block.html.erb
<div class="user_show_friends">
  <div class="friends_count_title">
    <%= link_to("Friends(#{@user.friends.count})", friends_user_path(@user) ) %>
  </div>
  <div class="user_show_avatars">
    <% @friends.each do |friend| %>
        <%= link_to( image_tag(friend.show_avatar(:thumb)), friend) %>
    <% end %>
  </div>
</div>

app/views/users/_user_list_block.html.erb
<div class="user_list_block">
  <% if current_user.friend?(user) %>
      <%= link_to 'Remove', current_user.relationships.find_by(friend_id: user.id),
                  method: :delete, data: { confirm: "Really remove #{user.login} from friends?" },
                  class: 'btn btn-danger user_list_link' %>

      <% if current_user.friends.include?(user) %>
          <%= form_for(current_user.conversations.build(recipient_id: user.id)) do |f| %>
              <%= f.hidden_field :recipient_id %>
              <%= f.submit 'Send message', class: 'btn btn-default user_list_link' %>
          <% end %>

      <% elsif @show_accept_block %>
        <%= form_for(current_user.relationships.find_by(friend_id: user.id)) do |f| %>
            <%= f.submit 'Accept', class: 'btn btn-info list_button' %>
        <% end %>
      <% end %>

  <% else %>
      <%= form_for(current_user.relationships.build(friend_id: user.id)) do |f| %>
          <%= f.hidden_field :friend_id %>
          <%= f.submit 'Add to a friends', class: 'btn btn-default' %>
      <% end %>
  <% end %>
</div>

app/views/users/_user_sidebar.html.erb
<div class="col-md-2">
  <div class="navbar navbar-default navbar-fixed-left">
    <% if current_user %>
      <ul class="nav navbar-nav">
        <li><%= link_to 'Settings', edit_user_path(current_user) %></li>
        <li><%= link_to 'Friends',  friends_user_path(current_user) %></li>
        <li><%= link_to "Messages #{ print_unread_message_count }", conversations_path, id: 'messages_link' %></li>
      </ul>
    <% else %>
      <%= link_to 'Sign in now', signin_path %>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<% provide(:title, 'Edit') %>
<div class="row">
  <%= render 'user_sidebar' %>
  <div class="col-xs-6 col-xs-offset-1">
    <h1>Edit profile</h1>
    <%= form_for(@user) do |f| %>

        <%= render 'shared/error_messages' %>

        <div class="form-group">
          <%= f.label :login %>
          <%= f.text_field :login, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :email %>
          <%= f.text_field :email, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :password %>
          <%= f.password_field :password, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :password_confirmation, 'Confirmation' %>
          <%= f.password_field :password_confirmation, class: 'form-control' %>
        </div>

        <%= f.label :avatar %>
        <div class="col-xs-6">
          <%= image_tag(@user.show_avatar(:original), alt: @user.login) %>
        </div>
        <div class="cols-xs-6">
          <%= f.file_field :avatar, 'data-filename-placement' => 'inside' %>
        </div>

        <%= f.submit 'Submit', class: 'btn btn-large btn-primary' %>
    <% end %>
  </div>
</div>

app/views/users/friends.html.erb
<% provide(:title, 'Friends') %>
<div class = "row">
  <%= render 'user_sidebar' %>
  <div class="col-md-9">
    <h1>Friends</h1>
    <div class = "row">
      <nav class="navbar navbar-light friend_type_panel">
        <ul class="nav navbar-nav">
          <li>
              <%= link_to 'Accepted Friends', friends_user_path(status: 'accepted') %>
          </li>
          <li>
            <%= link_to 'Pending acceptance', friends_user_path(status: 'pending') %>
          </li>
          <li>
            <%= link_to 'Requested friendship', friends_user_path(status: 'requested') %>
          </li>
        </ul>
      </nav>
    </div>
    <ul class="users">
      <%= render @users %>
    </ul>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'Users') %>
<div class = "row">
  <%= render 'user_sidebar' %>
  <div class="col-md-9">
    <h1>All users</h1>
    <%= will_paginate @users %>
    <ul class="users">
      <%= render @users %>
    </ul>
    <%= will_paginate @users %>
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign Up') %>
<h1>Sign up</h1>
<div class="row">
  <div class="col-xs-6 col-xs-offset-3">
    <%= form_for(@user) do |f| %>

      <%= render 'shared/error_messages' %>

      <div class="form-group">
        <%= f.label :login %>
        <%= f.text_field :login, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :email %>
        <%= f.text_field :email, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, 'Confirmation' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :avatar %>
        <%= f.file_field :avatar, class: 'form-control', 'data-filename-placement' => 'inside' %>
      </div>

      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.login ) %>
<div class = "row">
  <%= render 'user_sidebar' %>
  <div class="col-md-3">
    <div class="navbar navbar-default navbar-fixed-left">
      <%= image_tag(@user.show_avatar(:original), alt: @user.login) %>
      <span class="user_login_show">
        <%= @user.login %>
      </span>
      <% if @user.online? %>
        <span class="online">
          online
        </span>
      <% end %>
      <%= render 'user_conversation_block' %>
      <%= render 'user_friends_block' %>
    </div>
  </div>
  <div class="col-md-6">
    <div class="row">
      <h2>Left side Navigation bar (Fixed)</h2>
      <p>Значимость этих проблем настолько очевидна, что укрепление и развитие структуры позволяет оценить значение дальнейших направлений развития. Разнообразный и богатый опыт дальнейшее развитие различных форм деятельности позволяет выполнять важные задания по разработке систем массового участия. Значимость этих проблем настолько очевидна, что начало повседневной работы по формированию позиции обеспечивает широкому кругу (специалистов) участие в формировании позиций, занимаемых участниками в отношении поставленных задач. Равным образом постоянный количественный рост и сфера нашей активности позволяет оценить значение систем массового участия. Значимость этих проблем настолько очевидна, что постоянное информационно-пропагандистское обеспечение нашей деятельности представляет собой интересный эксперимент проверки существенных финансовых и административных условий. Не следует, однако забывать, что рамки и место обучения кадров требуют от нас анализа направлений прогрессивного развития.</p>
    </div>
  </div>
</div>