config/routes.rb
Rails.application.routes.draw do

  root 'sessions#new'

  resources :users do
    member do
      get :confirm_email
      get :friends
    end
  end

  resources :sessions, only: [:new, :create, :destroy]
  resources :reset_password, expect: [:destroy]
  resources :relationships, only: [:create, :update, :destroy]
  resources :conversations, expect: [:edit, :update]
  resources :messages, only: [:create]
  resources :rooms, only: [:create, :show, :destroy]

  get '/signup' => 'users#new'
  get '/signin' => 'sessions#new'
  delete '/signout' => 'sessions#destroy'

  get '/help' => 'static_pages#help'
  get '/about' => 'static_pages#about'
  post '/htmlparse' => 'base_chat#html_parse'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    by Ruslan Khabibullin
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", '#' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar  navbar-static-top navbar-default">
    <div class="container">
        <% if signed_in? %>

          <div class="navbar-header">
            <%= link_to "Some_Chat", current_user , id: 'logo' %>
          </div>
          <ul class="nav pull-right navbar-nav">

            <li class=<%= active_class(user_path(current_user)) %>>
              <%= link_to "Home", current_user %></li>

            <li class=<%= active_class(users_path) %>>
              <%= link_to "Users", users_path %></li>

            <li class=<%= active_class(help_path) %>>
              <%= link_to "Help", help_path %></li>

            <li><%= link_to "Sign out", signout_path, method: :delete %></li>
          </ul>

        <% else %>

          <div class="navbar-header">
              <%= link_to "Some_Chat", root_path , id: 'logo' %>
          </div>
            <ul class="nav pull-right navbar-nav">
              <li class=<%= active_class(signin_path) %>>
                <%= link_to "Sign in", root_path %></li>

              <li class=<%=  active_class(help_path) %>>
                <%= link_to "Help", help_path %></li>
            </ul>

        <% end %>
  </div>
</header>

app/views/layouts/_link_preview.html.erb
<div id="link_preview" class="link_preview">
  <div class="row">
    <div class="col-md-2">
      <img id="link_image">
    </div>
    <div class="col-md-8 col-md-offset-1">
      <span id="link_title"></span>
      <span id="description_link"></span>
      <a id="link_url"></a>
    </div>
  </div>
</div>

app/views/layouts/_messages_list.html.erb
<div class="row">
  <div class="search-input">
    <% if @messages.present? %>
      <%= form_tag socket_message_route(@messages.last), :method => 'get' do %>
        <div class="col-md-10">
          <%= text_field_tag :search, params[:search], class: "form-control" %>
        </div>
        <div class="col-md-2">
          <%= submit_tag "Search", class: "btn btn-info" %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>
<div class="row text-center">
  <%= link_to "Show Previous",  "?m=all" %>
</div>
<div class = "row">
  <div class="message_overflow">
    <ul class="messages">
      <% if @messages.empty? %>
          <p>No messages yet</p>
      <% else %>
          <%= render @messages %>
      <% end %>
    </ul>
  </div>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>
      <%= yield(:title) %>
    </title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>

    <%= render 'layouts/header' %>
      <div class="container">

        <% flash.each do |key, value| %>
          <div class="alert alert-<%= key %>">
            <%= value %>
          </div>
        <% end %>

        <%= yield %>

        <%= render 'layouts/footer' %>

        <%= debug(params) if Rails.env.development? %>

      </div>

      <script>
        $(document).ready(function(){
          $('input[type=file]').bootstrapFileInput();
        });
      </script>

  </body>
</html>